version: '3'
services:
  # admin-app:
  #   build: ./admin/admin-app
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./admin/admin-app/src:/app/src
  #     - ./admin/admin-app/public:/app/public
  #     - ./admin/admin-app/tsconfig.json:/app/tsconfig.json
  #     - ./admin/admin-app/vite.config.ts:/app/vite.config.ts
  #   environment:
  #     - NODE_ENV=development

api-services:
  build:
    context: ./api/services
    dockerfile: Dockerfile.dev
  ports:
    - "4000:4000"
  volumes:
    - ./api/services:/app
  environment:
    - NODE_ENV=development
    - PORT=4000
