name: Create trimmed deploy bundle

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: |
          chmod +x scripts/create-trimmed-deploy-zip.sh

      - name: Create trimmed bundle
        run: |
          ./scripts/create-trimmed-deploy-zip.sh

      - name: Upload trimmed bundle
        uses: actions/upload-artifact@v4
        with:
          name: flomingo-deploy-trim
          path: flomingo-deploy-trim.zip
