name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # or main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (for AWS CLI & EB CLI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install AWS CLI & EB CLI
        run: |
          pip install --upgrade pip
          pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy frontend
        run: |
          cd admin/admin-app
          eb init ${{ secrets.EB_APP_NAME }} --platform docker --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_ENV_NAME }}
          eb deploy

      - name: Deploy API services
        run: |
          cd ../../api/services
          eb init ${{ secrets.EB_SERVICES_NAME }} --platform docker --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_SERVICES_ENV_NAME }}
          eb deploy